# Generated by Django 4.2.2 on 2023-06-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inactiveitems',
            name='Final_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
