# Generated by Django 4.2.2 on 2023-06-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.ImageField(upload_to='auctions/images/'),
        ),
    ]
