# Generated by Django 4.2.2 on 2023-06-20 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_first_name_alter_user_last_name_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='item',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inactiveitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='items',
            name='seller',
        ),
        migrations.AddField(
            model_name='activeitems',
            name='item',
            field=models.ManyToManyField(related_name='ActiveItems', to='auctions.items'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.ManyToManyField(related_name='Bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ManyToManyField(related_name='Bids', to='auctions.items'),
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ManyToManyField(related_name='Comments', to='auctions.items'),
        ),
        migrations.AddField(
            model_name='inactiveitems',
            name='item',
            field=models.ManyToManyField(related_name='InactiveItems', to='auctions.items'),
        ),
        migrations.AddField(
            model_name='items',
            name='seller',
            field=models.ManyToManyField(related_name='Listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
