# Generated by Django 4.2.2 on 2023-06-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_items_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeitems',
            old_name='Current_price',
            new_name='Current_Price',
        ),
    ]
