# Generated by Django 4.2.2 on 2023-06-22 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='starting_price',
            new_name='Starting_price',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='items',
            name='seller',
        ),
        migrations.AddField(
            model_name='items',
            name='Seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
